# Site settings
title: Alexander Büsser
description: 'Business Card Page'
url: 'https://www.zuehlke.cloud'
baseurl: ''
profilepic: '/images/ajb.jpeg'
bkimage: '/images/cover.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '94f5e5625f.js'

author:
  name: 'Alexander Büsser'
  email: aj.buesse@gmail.com
  twitter_username: AlexanderBusser
  github_username:  albu89
  linkedin_username:  abu89


defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: 
  - jekyll-paginate
  - jekyll-feed

paginate: 5
paginate_path: "/blog/page/:num/"

exclude: ['README.md', 'screenshot-overview.png']
